In [2]:
import pandas as pd 
import os
import sys
from pathlib import Path

os.chdir(Path().resolve().parent)
sys.path.append(str(Path().resolve()))

from src.pipeline import process_document, process_folder

In [4]:
docs = process_folder('data/raw')

In [10]:
df = pd.DataFrame([{
    'text': d['text'],
    'source': d['metadata']['source'],
    'page': d['metadata']['page'],
    'chunk_id': d['metadata']['chunk_id']
} for d in docs])
df.head()

                                                text   source  page  chunk_id
0  Предисловие \nЯ исключительно горжусь первым и...  121.pdf     1         0
1  Python 3.6 (и многие из его новых функций, так...  121.pdf     1         1
2  рые материалы, которые кажутся менее субъектив...  121.pdf     1         2
3  ♦курсив указывает на новые термины;\n♦моношири...  121.pdf     1         3
4  значениями пользователя либо значениями, опред...  121.pdf     1         4

In [11]:
df[df['source'] == 'Safari.pdf']

,text,source,page,chunk_id
1147,Окончив университет в юго-восточных штатах и п...,Safari.pdf,1,0
1148,будучи двумя близкими по духу перспективными с...,Safari.pdf,1,1
1149,Проработав несколько лет в условиях внутрикорп...,Safari.pdf,1,2
1150,(Флорида). Сара же выбрала местом стажировки к...,Safari.pdf,1,3
1151,Когда в середине июля у Сары закончилась стажи...,Safari.pdf,1,4
1152,электронное сообщение по адресу salesdardenbus...,Safari.pdf,1,5
1153,This document is authorised for use only т Exe...,Safari.pdf,1,6
1154,"По прошествии трех лет, одного месяца и 16 дне...",Safari.pdf,2,7
1155,В To чудесное воскресное утро Грег встретил ме...,Safari.pdf,2,8
1156,"Когда мы вышли на пляж, мы решили\nпройтись и ...",Safari.pdf,2,9
1157,"секунд, которые тянулись, KaK минуты, он\nсказ...",Safari.pdf,2,10
1158,"Грег посмотрел на меня и сказал, что хотел бы\...",Safari.pdf,2,11
1159,"Когда он произнес эти заветные слова, способны...",Safari.pdf,2,12
1160,This document is authorised for use only in Ex...,Safari.pdf,2,13
1161,3. UV0869\n\nИдеальное кольцо для помолвки\n\n...,Safari.pdf,3,14
1162,Если бы мы разрабатывали кейс по организационн...,Safari.pdf,3,15
1163,"С Toro самого момента, как OH решил сделать пр...",Safari.pdf,3,16
1164,У меня не очень получалось подобрать кольцо и ...,Safari.pdf,3,17
1165,"хотел, чтобы она был идеальной без каких-либо ...",Safari.pdf,3,18
1166,"У меня оставалось около месяца до дня, когда я...",Safari.pdf,3,19
1167,"Итак, решение было найдено. Я должен был купит...",Safari.pdf,3,20
1168,выборе бриллианта. Всего несколько запросов в ...,Safari.pdf,3,21
1169,4. UV0869\n\nОценка бриллиантов зависит от чет...,Safari.pdf,4,22
1170,"Огранка: В 1919 году Марсель Толковский, молод...",Safari.pdf,4,23
1171,и преломлять свет. По этой причине огранка бри...,Safari.pdf,4,24
1172,"Цвет: Цвет в бриллиантах действует как фильтр,...",Safari.pdf,4,25
1173,Табл. 1. Шкала цвета бриллиантов.\n\nКласс Опи...,Safari.pdf,4,26
1174,- Заметный цвет Легко обнаруживается глазом не...,Safari.pdf,4,27
1175,slight inclusions — крайне незначительные вклю...,Safari.pdf,4,28
1176,"5. UV0869\n\nBec в каратах: Наконец, размер яв...",Safari.pdf,5,29
1177,Прочие факторы: Большинство бриллиантов ювелир...,Safari.pdf,5,30
1178,качество и потенциально увеличивает его стоимо...,Safari.pdf,5,31
1179,Симметрия orpaHKH и — полировка — поверхностей...,Safari.pdf,5,32
1180,Ежемесячное издание Rapaport Diamond Report (R...,Safari.pdf,5,33
1181,"К сожалению, из-за использования обширного мат...",Safari.pdf,5,34
1182,Имея доступ к обширным исследованиям рынка и о...,Safari.pdf,5,35
1183,"собирался использовать эти данные, чтобы постр...",Safari.pdf,5,36
1184,This document is authorised for use only in Ex...,Safari.pdf,5,37
1185,-9- UV0869\n\nПриложение 1\nБРИЛЛИАНТ ДЛЯ САРЫ...,Safari.pdf,6,38